### PR TITLE
Automatically Color Units: Compatibility patch for LW_Toolbox

### PR DESCRIPTION
**Pull request by robojumper**
Merge UIScreenListener classes to one, omitting a defaultproperty so that it triggers on every screen.
I didn't change anything, just merged the classes extending UIScreenListener (listening to UISquadSelect, UIArmory_MainMenu, UIArmory_PromotionPsiOp, UISquadSelect).
[Implementation based on the suggestion of LW Dev Amineri](https://forums.nexusmods.com/index.php?/topic/4070425-screen-listeners-and-ui-overrides/?p=37289105).

### CODE REVIEW

**Comment by BlueRaja** [comment]
Why did you create a second commit to replace spaces with tabs?  That's breaks away from the style of the original code _(and the rest of the repo)_.

**Comment by robojumper** [comment]
Oops, thought tabs were the preferred form because the spaces were looking funny. My bad, fixing it.

**Comment by robojumper** [comment]
Should I add a 

```
defaultproperties
{
    ScreenClass = none;
}
```

at the end? It is probably redundant, but doesn't hurt.

**Comment by BlueRaja** [comment]
Yes, please do.

**Pull request merged**
